//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 09:37:08 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.lb.lt/ExchangeRates", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap.wsdl_gen;
